use AssignmentsQuery
go

CREATE TABLE CLIENTS(
CLIENT_ID int PRIMARY KEY,
CNAME varchar(40) NOT NULL,
ADDRESS varchar(30),
EMAIL varchar(30) UNIQUE,
PHONE varchar(10),
BUSINESS varchar(20) NOT NULL)
go

Insert into CLIENTS(CLIENT_ID,CNAME,ADDRESS,EMAIL,PHONE,BUSINESS) values 
(1001,'ACMEUtilities','Noida','contact@acmeutil.com',9567880032,'Manufacturing')
Insert into CLIENTS(CLIENT_ID,CNAME,ADDRESS,EMAIL,PHONE,BUSINESS) values 
(1002,'TrackonConsultants','Mumbai','consult@trackon.com',8734210090,'Consultant')
Insert into CLIENTS(CLIENT_ID,CNAME,ADDRESS,EMAIL,PHONE,BUSINESS) values 
(1003,'MoneySaverDistributors','Bangalore','save@moneysaver.com',7799886655,'Reseller')
Insert into CLIENTS(CLIENT_ID,CNAME,ADDRESS,EMAIL,PHONE,BUSINESS) values 
(1004,'LawfulCorp','Chennai','justice@lawful.com',9210342219,'Professional')
go

CREATE TABLE DEPARTMENTS(
DEPTNO int PRIMARY KEY,
DNAME varchar(40) NOT NULL,
LOC varchar(20))
go

Insert into DEPARTMENTS (DEPTNO,DNAME,LOC) values
(10,'Design','Pune')
Insert into DEPARTMENTS (DEPTNO,DNAME,LOC) values
(20,'Development','Pune')
Insert into DEPARTMENTS (DEPTNO,DNAME,LOC) values
(30,'Testing','Mumbai')
Insert into DEPARTMENTS (DEPTNO,DNAME,LOC) values
(40,'Document','Mumbai')
go

CREATE TABLE EMPLOYEES(
EMPNO int PRIMARY KEY,
ENAME varchar(20) NOT NULL,
JOB varchar(15),
SALARY decimal(30) CHECK (SALARY > 0),
DEPTNO int FOREIGN KEY references
DEPARTMENTS(DEPTNO))
go


Insert into EMPLOYEES(EMPNO,ENAME,JOB,SALARY,DEPTNO) values
(7001,'Sandeep','Analyst',25000,10)
Insert into EMPLOYEES(EMPNO,ENAME,JOB,SALARY,DEPTNO) values
(7002,'Rajesh','Designer',30000,10)
Insert into EMPLOYEES(EMPNO,ENAME,JOB,SALARY,DEPTNO) values
(7003,'Madhav','Developer',40000,20)
Insert into EMPLOYEES(EMPNO,ENAME,JOB,SALARY,DEPTNO) values
(7004,'Manoj','Developer',40000,20)
go

CREATE TABLE PROJECTS(
PROJECT_ID int PRIMARY KEY,
DESCR varchar(30) NOT NULL,
START_DATE DATE,
PLANNED_END_DATE DATE,
ACTUAL_END_DATE DATE,
BUDGET int CHECK(BUDGET > 0),
CLIENT_ID int FOREIGN KEY  REFERENCES
CLIENTS(CLIENT_ID))
go


Insert into PROJECTS(PROJECT_ID,DESCR,START_DATE,PLANNED_END_DATE, ACTUAL_END_DATE,BUDGET,CLIENT_ID) values
(401,'Inventory',CONVERT(DATETIME, '01-APR-19'),CONVERT(DATETIME, '10-JUN-19'),CONVERT(DATETIME, '11-DEC-19'),150000,1001)

Insert into PROJECTS(PROJECT_ID,DESCR,START_DATE,PLANNED_END_DATE,ACTUAL_END_DATE,BUDGET,CLIENT_ID) values
(402,'Accounting',CONVERT(DATETIME, '21-SEP-20'),CONVERT(DATETIME, '01-DEC-20'),CONVERT(DATETIME, '01-APR-11'), 500000,1002)

Insert into PROJECTS(PROJECT_ID,DESCR,START_DATE,PLANNED_END_DATE,ACTUAL_END_DATE,BUDGET,CLIENT_ID) values
(403,'Payroll',CONVERT(DATETIME, '01-JAN-21'),CONVERT(DATETIME, '01-MAY-21'),null,75000,1003)
go

CREATE TABLE EMPPROJECTTASKS(
PROJECT_ID int FOREIGN KEY  REFERENCES
PROJECTS(PROJECT_ID),
EMPNO int FOREIGN KEY  REFERENCES EMPLOYEES(EMPNO),
START_DATE DATE,
END_DATE DATE,
TASK varchar(25) NOT NULL,
STATUS varchar(15) NOT NULL,
PRIMARY KEY(PROJECT_ID,EMPNO))
go


Insert into EMPPROJECTTASKS(PROJECT_ID,EMPNO,START_DATE,END_DATE,TASK,STATUS) values 
(401,7001,CONVERT(DATETIME, '01-JAN-18'),CONVERT(DATETIME, '01-APR-18'),'SystemAnalysis','Completed')
Insert into EMPPROJECTTASKS(PROJECT_ID,EMPNO,START_DATE,END_DATE,TASK,STATUS) values 
(401,7002,CONVERT(DATETIME, '01-DEC-18'),CONVERT(DATETIME, '01-APR-19'),'SystemDesign','Completed')
Insert into EMPPROJECTTASKS(PROJECT_ID,EMPNO,START_DATE,END_DATE,TASK,STATUS) values 
(401,7003,CONVERT(DATETIME, '15-JAN-19'),CONVERT(DATETIME, '22-NOV-19'),'Coding','Completed')
Insert into EMPPROJECTTASKS(PROJECT_ID,EMPNO,START_DATE,END_DATE,TASK,STATUS) values 
(401,7004,CONVERT(DATETIME, '11-FEB-20'),CONVERT(DATETIME, '21-SEP-21'),'Coding','Completed')
Insert into EMPPROJECTTASKS(PROJECT_ID,EMPNO,START_DATE,END_DATE,TASK,STATUS) values 
(401,7006,CONVERT(DATETIME, '01-JAN-21'),CONVERT(DATETIME, '31-DEC-21'),'Testing','Completed')
Insert into EMPPROJECTTASKS(PROJECT_ID,EMPNO,START_DATE,END_DATE,TASK,STATUS) values 
(401,7009,CONVERT(DATETIME,'01-MAR-19'),CONVERT(DATETIME, '01-JAN-22'),'CodeChange','Completed')
go
update EMPPROJECTTASKS set STATUS = 'Inprogress' where EMPNO = 7006
go
SELECT * FROM CLIENTS
SELECT * FROM DEPARTMENTS
SELECT * FROM EMPLOYEES
SELECT * FROM PROJECTS
SELECT * FROM EMPPROJECTTASKS

----------Assignments_1 Que ANS ------

------ANS of QUE NO. 1-----------

SELECT * FROM CLIENTS WHERE BUSINESS = 'Consultant'

------ANS of QUE NO. 2-----------

select * from EMPLOYEES where JOB <> 'Developer'

------ANS of QUE NO. 3-----------

select * from PROJECTS where budget > 100000

------ANS of QUE NO. 4-----------

SELECT * FROM PROJECTS WHERE ACTUAL_END_DATE IS NOT NULL

------ANS of QUE NO. 5-----------
select * from EMPLOYEES where ENAME like 'M%'

------ANS of QUE NO. 6-----------
SELECT * FROM EMPLOYEES WHERE ENAME LIKE '%a'

------ANS of QUE NO. 7-----------

SELECT * FROM PROJECTS as month WHERE DESCR = 'Inventory';

------ANS of QUE NO. 8-----------

SELECT * FROM EMPPROJECTTASKS WHERE STATUS = 'In Progress'

------ANS of QUE NO. 9-----------

SELECT * FROM DEPARTMENTS WHERE LOC = 'Pune'

------ANS of QUE NO. 10-----------
SELECT ENAME,SALARY FROM EMPLOYEES ORDER BY SALARY DESC

------ANS of QUE NO. 11-----------

SELECT TASK,END_DATE FROM EMPPROJECTTASKS ORDER BY END_DATE

------ANS of QUE NO. 12-----------

SELECT DISTINCT JOB FROM EMPLOYEES

------ANS of QUE NO. 13-----------

SELECT UPPER(ENAME) FROM EMPLOYEES

------ANS of QUE NO. 14-----------

SELECT  ENAME,SALARY, SALARY * .25 AS BONUS FROM EMPLOYEES

------ANS of QUE NO. 15-----------

 SELECT ENAME + ' Works As '+ JOB FROM EMPLOYEES

------ANS of QUE NO. 16-----------


SELECT DATENAME(WEEKDAY, START_DATE) AS WeeDay from PROJECTS


------ANS of QUE NO. 17-----------

SELECT EMAIL,CHARINDEX('@',EMAIL,1) FROM CLIENTS

------ANS of QUE NO. 18-----------

SELECT ENAME,SUBSTRING(ENAME,1,3) FROM EMPLOYEES

------ANS of QUE NO. 19-----------

SELECT format(BUDGET ,'C') FROM PROJECTS

------ANS of QUE NO. 20-----------

SELECT PLANNED_END_DATE, DATENAME(day,3) AS REVIEW_DATE FROM PROJECTS


-------Assignments_2 Que  ANS---------

------ANS of QUE NO. 1-----------

SELECT COUNT(*) FROM CLIENTS

------ANS of QUE NO. 2-----------

SELECT COUNT(*) AS NOE,SUM(SALARY) AS SUMSAL FROM EMPLOYEES

------ANS of QUE NO. 3-----------

SELECT DEPTNO,MAX(SALARY) FROM EMPLOYEES GROUP BY DEPTNO

------ANS of QUE NO. 4-----------

SELECT JOB,MIN(SALARY) FROM EMPLOYEES GROUP BY JOB

------ANS of QUE NO. 5-----------

SELECT (AVG(SALARY)) FROM EMPLOYEES

------ANS of QUE NO. 6-----------

SELECT SUM(BUDGET) FROM PROJECTS

------ANS of QUE NO. 7-----------

SELECT COUNT(*) FROM EMPPROJECTTASKS WHERE TASK= 'Coding'

------ANS of QUE NO. 8-----------

SELECT DEPTNO,COUNT(*),SUM(SALARY) FROM EMPLOYEES GROUP BY DEPTNO

------ANS of QUE NO. 9-----------

SELECT C.CNAME,P.DESCR,P.START_DATE,P.BUDGET FROM CLIENTS C, PROJECTS P WHERE
P.CLIENT_ID = C.CLIENT_ID

------ANS of QUE NO. 10-----------

SELECT D.DNAME,E.ENAME, E.JOB FROM DEPARTMENTS D,EMPLOYEES E WHERE D.DEPTNO = E.DEPTNO

------ANS of QUE NO. 11-----------

SELECT E.ENAME,P.DESCR FROM EMPLOYEES E,PROJECTS P,EMPPROJECTTASKS T WHERE
T.PROJECT_ID = P.PROJECT_ID AND T.EMPNO = E.EMPNO AND T.TASK = 'System Analysis'

------ANS of QUE NO. 12-----------

SELECT JOB,COUNT(*) FROM EMPLOYEES GROUP BY JOB

------ANS of QUE NO. 13-----------

SELECT EMPNO FROM EMPLOYEES MINUS SELECT EMPNO FROM EMPPROJECTTASKS

------ANS of QUE NO. 14-----------

SELECT EMPNO FROM EMPLOYEES
INTERSECT SELECT EMPNO FROM EMPPROJECTTASKS

------ANS of QUE NO. 15-----------

SELECT EMPNO FROM EMPLOYEES
UNION ALL SELECT EMPNO FROM EMPPROJECTTASKS








